Added Support for Apple Silicon M1
databus23/helm-diff pull request #264
Opened 2021-03-04 14:44 UTC by f3lan

I simply added the architecture to the supported list. I tested this on
my Mac and it worked.

2021-05-19 06:14 UTC, abh approved these changes
looks good to me ...

2021-09-17 17:09 UTC, dmerrick commented
I'm interested in this!

2021-09-21 15:19 UTC, dmerrick requested changes

2021-09-22 11:34 UTC, f3lan commented on install-binary.sh
> +  supported="linux-amd64\nfreebsd-amd64\nmacos-amd64\macos-arm64\nwindows-amd64"
hi @dmerrick That is completely true. Im sorry for this bad mistake. I corrected this with my last commit.

2021-12-17 03:08 UTC, yseymour commented
This looks to have been merged in #294.

2021-12-17 14:04 UTC, Hammond95 commented
I think this can be closed since #294 has been merged.

2022-01-08 08:50 UTC, mumoshu commented
Yep. This can be closed and it should install fine on M1 mac now! Thanks for your patience and support everyone

2022-01-08 08:50 UTC, closed without merging